
set(ENABLED_GEMS
    Hitboy_Remastered
    Atom
    AudioSystem
    AWSCore
    CameraFramework
    DebugDraw
    EditorPythonBindings
    EMotionFX
    GameState
    ImGui
    LandscapeCanvas
    LyShine
    Multiplayer
    PhysX
    PrimitiveAssets
    SaveData
    ScriptCanvasPhysics
    ScriptEvents
    StartingPointInput
    TextureAtlas
    WhiteBox
    AWSClientAuth
    AWSGameLift
    AWSMetrics
    Achievements
    AssetMemoryAnalyzer
    AssetValidation
    AtomContent
    DccScriptingInterface
    AtomLyIntegration
    AtomTressFX
    BarrierInput
    Camera
    CrashReporting
    CustomAssetExample
    DevTextures
    FastNoise
    GameStateSamples
    Gestures
    InAppPurchases
    Maestro
    Metastream
    Microphone
    MultiplayerCompression
    Blast
    NvCloth
    PhysXDebug
    PrefabBuilder
    Presence
    Profiler
    QtForPython
    SceneLoggingExample
    SceneProcessing
    ScriptCanvasDeveloperGem
    ScriptCanvasTesting
    ScriptedEntityTweener
    SliceFavorites
    StartingPointCamera
    StartingPointMovement
    
    TestAssetBuilder
    TickBusOrderViewer
    Twitch
    VideoPlaybackFramework
    VirtualGamepad
    AudioEngineWwise
)
